# Generated by Django 4.1.7 on 2023-02-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosVenta', '0002_cliente_auto_image_auto_dni_anterior_duenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='patente',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='auto',
            name='precio',
            field=models.IntegerField(default=None),
        ),
    ]
