# Generated by Django 4.1.7 on 2023-02-27 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosVenta', '0004_remove_auto_id_alter_auto_dni_anterior_duenio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='auto_vendido',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='serviciosVenta.auto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='servicio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='serviciosVenta.servicio'),
        ),
    ]
