# Generated by Django 4.1.7 on 2023-02-27 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosVenta', '0005_alter_factura_auto_vendido_alter_factura_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='auto_vendido',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='servicio',
        ),
    ]
