# Generated by Django 4.1.7 on 2023-03-22 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosVenta', '0007_factura_descripcion_extra_factura_detalle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='dni_anterior_duenio',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
