# Generated by Django 4.1.7 on 2023-03-23 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosVenta', '0008_delete_factura_remove_auto_dni_anterior_duenio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'ordering': ['-disponible']},
        ),
    ]
